apiVersion: v1
kind: Secret
metadata:
  name: acr-secret         
  namespace: grafana   
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "ewoJImF1dGhzIjogewoJCSJsaXRtdXMuYXp1cmVjci5pbyI6IHsKCQkJInVzZXJuYW1lIjogImxpdG11cyIsCgkJCSJwYXNzd29yZCI6ICJhRThRZ2hwbzhrMlRVM0QzcytLMU00bkhpellTYytndFBoRlFDT0FReHorQUNSQU1GeHhPIiwKCQkJImF1dGgiOiAiYkdsMGJYVnpPbUZGT0ZGbmFIQnZPR3N5VkZVelJETnpLMHN4VFRSdVNHbDZXVk5qSzJkMFVHaEdVVU5QUVZGNGVpdEJRMUpCVFVaNGVFOD0iCgkJfQoJfQp9Cg=="
