# Create ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: litmusedge-docker
  namespace: le-prod
  labels:
    app.kubernetes.io/name: litmusedge-docker
    app.kubernetes.io/instance: litmusedge-instance
---
# Create PVC
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: litmusedge-data
  namespace: le-prod
  labels:
    app.kubernetes.io/name: litmusedge-docker
    app.kubernetes.io/instance: litmusedge-instance
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10G"
---
# Create Service
apiVersion: v1
kind: Service
metadata:
  name: litmusedge-docker
  namespace: le-prod
  labels:
    app.kubernetes.io/name: litmusedge-docker
    app.kubernetes.io/instance: litmusedge-instance
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: litmusedge-docker
    app.kubernetes.io/instance: litmusedge-instance
---
# Create Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: litmusedge-docker
  namespace: le-prod
  labels:
    app.kubernetes.io/name: litmusedge-docker
    app.kubernetes.io/instance: litmusedge-instance
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: litmusedge-docker
      app.kubernetes.io/instance: litmusedge-instance
  template:
    metadata:
      labels:
        app.kubernetes.io/name: litmusedge-docker
        app.kubernetes.io/instance: litmusedge-instance
    spec:
      serviceAccountName: litmusedge-docker
      securityContext:
        {}
      imagePullSecrets:
        - name: acr-secret  
      containers:
        - name: litmusedge-docker
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
          image: "litmus.azurecr.io/litmusedge-std-docker:3.16.2"
          imagePullPolicy: IfNotPresent
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          volumeMounts:
            - mountPath: /var
              mountPropagation: 
              name: litmusedge-data
              subPath: 
              subPathExpr: 
          resources:
            requests:
              cpu: 1
              memory: 1024Mi
            limits:
              cpu: 4
              memory: 4096Mi
      volumes:
        - name: litmusedge-data
          persistentVolumeClaim:
            claimName: litmusedge-data
