apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kkm

resources:
  - litmus-uns-namespace.yml
  - acr-secret.yml
  - litmusautomation-uns-centralportal-secret.yml
  - litmus-uns-edited-helm-values.yml
  - litmus-uns-helmrepository.yaml
  - litmus-uns-helmrelease.yaml